// AUTO-GENERATED by tools/build_words.py -- DO NOT EDIT
// 词库元数据：修改词库后请重新运行 python tools/build_words.py

import part00 from "./part_00.js";
import part01 from "./part_01.js";
import part02 from "./part_02.js";
import part03 from "./part_03.js";
import part04 from "./part_04.js";
import part05 from "./part_05.js";
import part06 from "./part_06.js";
import part07 from "./part_07.js";
import part08 from "./part_08.js";
import part09 from "./part_09.js";
import part10 from "./part_10.js";
import part11 from "./part_11.js";
import part12 from "./part_12.js";
import part13 from "./part_13.js";
import part14 from "./part_14.js";
import part15 from "./part_15.js";
import part16 from "./part_16.js";
import part17 from "./part_17.js";
import part18 from "./part_18.js";
import part19 from "./part_19.js";
import part20 from "./part_20.js";
import part21 from "./part_21.js";
import part22 from "./part_22.js";
import part23 from "./part_23.js";
import part24 from "./part_24.js";
import part25 from "./part_25.js";
import part26 from "./part_26.js";
import part27 from "./part_27.js";
import part28 from "./part_28.js";
import part29 from "./part_29.js";

// 每个分片的原始字符串（惰性解析，不要在启动时 split 全部）
const RAW_PARTS = [
  part00,
  part01,
  part02,
  part03,
  part04,
  part05,
  part06,
  part07,
  part08,
  part09,
  part10,
  part11,
  part12,
  part13,
  part14,
  part15,
  part16,
  part17,
  part18,
  part19,
  part20,
  part21,
  part22,
  part23,
  part24,
  part25,
  part26,
  part27,
  part28,
  part29
];

// 每个分片的词条数量（最后一片可能不足）
const PART_SIZES = [
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  200,
  9
];

export const META = {
  total: 5809,
  partCount: 30,
  perPart: 200,
  partSizes: PART_SIZES
};

export default RAW_PARTS;
